language: node_js

sudo: required

node_js:
 - "8"
 - "10"

branches:
  only:
    - master

services:
 - docker

install:
 - npm install

before_install:
 - npm run lint
 - docker pull telefonicaiot/fiware-orion
 - docker run --name mongodb -d mongo:3.4
 - docker run --name orion -d --link mongodb:mongodb -p 10026:1026 telefonicaiot/fiware-orion -dbhost mongodb

