language: node_js
sudo: required

branches:
  only:
    - master

services:
  - docker

jobs:
  include:
    - stage: test
      name: "Unit Tests: Node 8"
      node_js: 8

      before_install:
        - docker pull telefonicaiot/fiware-orion
        - docker run --name mongodb -d mongo:3.4
        - docker run --name orion -d --link mongodb:mongodb -p 10026:1026 telefonicaiot/fiware-orion -dbhost mongodb

      before_script:
        - npm run lint

      after_script:
        - npm run test:coveralls

    - stage: test
      name: "Unit Tests: Node 10"
      node_js: 10

      before_install:
        - docker pull telefonicaiot/fiware-orion
        - docker run --name mongodb -d mongo:3.4
        - docker run --name orion -d --link mongodb:mongodb -p 10026:1026 telefonicaiot/fiware-orion -dbhost mongodb

      before_script:
        - npm run lint

      after_script:
        - npm run test:coveralls

    - stage: test
      name: "Documentation Tests"
      node_js: 10

      script:
        - npm run lint:md
        - npm run lint:text
